### ISSUE TITLE
Browser Import with basic usage throws warnings

### ISSUE THREAD

**Issue by Novop** [dumptyd/vue-css-donut-chart#3] opened 2019-02-05 00:56 UTC
Also props don't seem to function.
i.e https://jsfiddle.net/cqp7xdjm/

Any ideas?

**Comment by dumptyd** [comment] 2019-02-05 02:00
I can't do anything about the warnings. If you check the browser console, you will notice that most of those warnings are coming from jsfiddle's own JS file and vue.

As for the props not working, that's on me. I have a habit of using camelCase props in my vue files but that doesn't work when you're writing vue templates in HTML since HTML attributes are case insensitive.
So changing `hasLegend` to `has-legend`, `legendPlacement` to `legend-placement` and so on should work. I will update the docs.

**Comment by Novop** [comment] 2019-02-06 00:16
The props are now working. Thanks for that.

In regards to the warnings:

[Vue warn]: Property or method "middle" is not defined on the instance but
referenced during render. Make sure that this property is reactive, either
in the data option, or for class-based components, by initializing the
property.
(found in <Root>)
vue.js:616:9
[Vue warn]: Invalid prop: custom validator check failed for prop "sections".
found in
---> <VcDonut> at Donut.vue

**Comment by dumptyd** [comment] 2019-02-06 06:50
Can you please post a fiddle reproducing these warnings?

**Comment by dumptyd** [comment] 2019-02-10 16:37
I've updated the docs. And I've tried many things to try to reproduce those warnings you're getting but I couldn't. Are you sure there wasn't some problem with your code? Cause I haven't used the word middle anywhere except for comments.

Anyway, I'm closing this for now. Feel free to re-open if you're still facing this issue.

**Closed as completed by dumptyd** 2019-02-10 16:37 UTC
Labels: bug
